language: node_js
node_js:
- 15
branches:
  only:
  - master
addons:
  ssh_known_hosts: nortung.dk
before_install:
- openssl aes-256-cbc -K $encrypted_0ddd2445e49f_key -iv $encrypted_0ddd2445e49f_iv
  -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
- chmod 600 ~/.ssh/travis_rsa
script:
- npm run build
- npm run generate
deploy:
  provider: script
  skip-cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
