language: node_js
node_js:
  - 15

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_1d290bd18850_key -iv $encrypted_1d290bd18850_iv
    -in .travis/travis_rsa.enc -out ~\/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa

script:
  - npm run build
  - npm run generate

deploy:
  provider: script
  skip-cleanup: true
  script: .travis/deploy.sh
  on:
    branch: master